services:
  web:
    build:
      context: .
    environment:
      RAILS_ENV: development
      DISABLE_SPRING: "1"
    command: bin/rails server --binding 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    stdin_open: true
    tty: true
